### ISSUE TITLE
Use git-url-parse 

### ISSUE THREAD

**Issue by andrewhughes101** [pkgjs/wiby#10]
Simplify the abstracting of a GitHub owner and repo from the Git url in the package.json by using [`git-url-parse'](https://www.npmjs.com/package/git-url-parse).

**Comment by rodion-arr** [comment]
@andrewhughes101 @BethGriggs 
I'm happy to help here if you don't mind

**Comment by dominykas** [comment]
It's still in my review queue, but isn't that covered in #14?

**Comment by rodion-arr** [comment]
Yeah, looks like it's already done
