### ISSUE TITLE
Enable linting as part of `npm test`

### ISSUE THREAD

**Issue by dominykas** [pkgjs/wiby#18]
First mentioned in https://github.com/pkgjs/wiby/pull/14#pullrequestreview-451685315:

> And it will be great to add `standard` command run to `test` script

While I wouldn't call `standard` "great" per se :trollface:, we might as well add it to the `npm test`, unless there's any objections or we plan to change the style?

**Comment by ljharb** [comment]
.Linting should be run in `pretest` (or `posttest`, i suppose, but pretest makes more sense to me), and CI should run `npm run pretest` once, and should have a way to only run the tests (i usually put them in a `tests-only` script) on all the covered nodes.

We definitely do plan to change the style, but we can update the pretest script at that time.

**Comment by rodion-arr** [comment]
Can I take this task?

**Comment by dominykas** [comment]
> pretest makes more sense to me

I don't care about it that much, but I'd rather posttest - it's more important to know early if the code does not work, rather than if the code does not look pretty enough, esp. when you're a new contributor trying to learn the codebase or just experimenting.

**Comment by ljharb** [comment]
The linter is about whether the code works, it's not just about how it looks. All linting rules - even style ones - prevent bugs.

**Comment by dominykas** [comment]
Sure, but the tests are specific to the project, while the pinter rules are abstract and generic. When tests are failing - you know you broke something now. When lint is failing - you only know you might be breaking something in the future. When you're working on a piece of code, you also want to fix the things that break tests first (or, in some cases, you just want to see which tests break when you make a change) - the linter just gets in the way, esp. if it has different rules than what you're accustomed to.

**Comment by ljharb** [comment]
I'm not sure what you mean - the linter would only be failing because of a change you made.

In my experience, fixing linting errors often fixes the tests anyways :-) either way, locally, it doesn't really matter what order `npm test` runs in, since everything runs in CI, as long as everything runs locally. Most folks have the linter running in their editor anyways, long before they check the tests, so they'll see and fix the linter warnings first regardless.
