### ISSUE TITLE
Support testing devDependecies (et al)

### ISSUE THREAD

**Issue by dominykas** [pkgjs/wiby#55]
At the moment `wiby` will check that the parent module is one of `dependencies` - but it could as well be in `devDependencies` or even `peerDependencies`.

**Comment by dominykas** [comment]
@ghinks how about this one?

**Comment by ghinks** [comment]
ok, looking into this one first :)

**Comment by ljharb** [comment]
(or optionalDependencies or bundleDependencies)

**Comment by ghinks** [comment]
I think we can close this issue under [PR 84](https://github.com/pkgjs/wiby/pull/84)
