### ISSUE TITLE
semantic-release bot is quite noisy

### ISSUE THREAD

**Issue by rodion-arr** [pkgjs/wiby#70]
Hi Team! 

I'd like disable [`successComment`](https://github.com/semantic-release/github#successcomment) option on `semantic-release` bot in order to prevent it from commenting under each released PR/issue.

WDYT?

**Comment by ljharb** [comment]
I also find it incredibly noisy.

**Comment by dominykas** [comment]
I find it useful to know which version a certain issue came out in... are there alternatives to that?

I think the noise mostly came from this release, because it's the first actual release of code. Going forward it should be less noisy, as long as we release frequently?

**Comment by ljharb** [comment]
You can click on the commit that closed the relevant PR, and it will list which version tags it’s included in. This works on every repo that tags versions, whether they use a comment bot or not.

**Comment by dominykas** [comment]
Yeah, you have to know that though.

I also just spotted that Refined Github does that too, which is pretty awesome.

I find these comments useful, and they might be useful for others, but I'm not strongly against getting rid of them either.
