### ISSUE TITLE
default branch master => main 

### ISSUE THREAD

**Issue by ghinks** [pkgjs/wiby#75]
could we co-ordinate some time in the near future to switch the default branch name?

**Comment by ljharb** [comment]
Given the new renaming features have landed, it should be as simple as changing the settings, after landing a commit that changes all `master`s to `HEAD` (which can land regardless).

**Comment by dominykas** [comment]
#77 covers the remaining mentions of `master` in this repo - I think we can do the rename once that's merged?

**Comment by ghinks** [comment]
Thank you
