### ISSUE TITLE
`wiby clean` command

### ISSUE THREAD

**Issue by dominykas** [pkgjs/wiby#79]
At the moment, `wiby test` creates a branch called `wiby-[dep name]` in the dependent repos. There is nothing to clean this up - running a new `wiby test` will fail if the branch already exists.

`wiby test` should not fail on existing branch - but that is a separate, larger problem (I'll create a separate issue), but in the meantime - deleting the `wiby-wiby` branch manually on `wiby-test/*` repos is a hassle during development.

`wiby clean` should take the following options:

- `--all` - remove all `wiby-*` branches (by default only remove the current branch, based on the naming as proposed in #78)
- `--dry-run` - show the branches that would be removed
    - alternative: do the dry-run by default and ask the user to confirm the action? With an optional `--force` to skip the confirmation?
    - bonus points: what if the branches contain commits other than ones made by wiby?

**Comment by ghinks** [comment]
I"ll have a look at this if you are not already doing so?

**Comment by dominykas** [comment]
I'm almost done with this.
