### ISSUE TITLE
Investigate repository_dispatch

### ISSUE THREAD

**Issue by bnb** [pkgjs/wiby#88]
Per the discussion in today's meeting, wanted to create an issue for checking out the [repository_dispatch](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#repository_dispatch) trigger for an Action, which allows an Action to be triggered by a GitHub API call. This might be useful for triggering an Action in the root Wiby repo to report back when a run fails/succeeds.

**Comment by dominykas** [comment]
Thanks! This does look useful, but since we can't rely on the target repos talking back to the parent repo, this still means having something external to trigger it, I think...

**Comment by dominykas** [comment]
Went through the docs again - `repository_dispatch` event needs _something_ to call the [`POST /repos/{owner}/{repo}/dispatches`](https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event) endpoint.

The only way I can imagine this working is to create some sort of a wiby "callback" workflow on the target dependent repo, but that probably defeats the purpose

I'll close this for now and keep on thinking thinking thinking...
