### ISSUE TITLE
Tests on main are failing

### ISSUE THREAD

**Issue by rodion-arr** [pkgjs/wiby#90]
Hi Team,

I noticed that tests on main are red - https://github.com/pkgjs/wiby/actions?query=branch%3Amain

Just wanted to clarify is it known issue or I can work on the fix?

**Comment by dominykas** [comment]
Actually, let me do it now.

**Comment by dominykas** [comment]
`main` is now green, but the tap upgrade still failing, if you're up for it.

**Comment by rodion-arr** [comment]
Thanks, I'll check tap upgrade
